//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyInfoHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyInfoHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show App infos and releases ähnelt.
        /// </summary>
        public static string AppInfoButtonToolTipString {
            get {
                return ResourceManager.GetString("AppInfoButtonToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company ähnelt.
        /// </summary>
        public static string AssemblyCompanyString {
            get {
                return ResourceManager.GetString("AssemblyCompanyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright ähnelt.
        /// </summary>
        public static string AssemblyCopyrightString {
            get {
                return ResourceManager.GetString("AssemblyCopyrightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation Time ähnelt.
        /// </summary>
        public static string AssemblyCreationTime {
            get {
                return ResourceManager.GetString("AssemblyCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string AssemblyDescriptionString {
            get {
                return ResourceManager.GetString("AssemblyDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Version ähnelt.
        /// </summary>
        public static string AssemblyFileVersionString {
            get {
                return ResourceManager.GetString("AssemblyFileVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informational Version ähnelt.
        /// </summary>
        public static string AssemblyInformationalVersionString {
            get {
                return ResourceManager.GetString("AssemblyInformationalVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product ähnelt.
        /// </summary>
        public static string AssemblyProductString {
            get {
                return ResourceManager.GetString("AssemblyProductString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string AssemblyTitleString {
            get {
                return ResourceManager.GetString("AssemblyTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trademark ähnelt.
        /// </summary>
        public static string AssemblyTrademarkString {
            get {
                return ResourceManager.GetString("AssemblyTrademarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string AssemblyVersionString {
            get {
                return ResourceManager.GetString("AssemblyVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string ChangelogString {
            get {
                return ResourceManager.GetString("ChangelogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downgrade ähnelt.
        /// </summary>
        public static string DowngradeString {
            get {
                return ResourceManager.GetString("DowngradeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Infos ähnelt.
        /// </summary>
        public static string GeneralInfosString {
            get {
                return ResourceManager.GetString("GeneralInfosString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Binary release is available for this version ähnelt.
        /// </summary>
        public static string GitHubBinaryReleaseAvailableString {
            get {
                return ResourceManager.GetString("GitHubBinaryReleaseAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installer release is available for this version ähnelt.
        /// </summary>
        public static string GitHubInstallerReleaseAvailableString {
            get {
                return ResourceManager.GetString("GitHubInstallerReleaseAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No releases available ähnelt.
        /// </summary>
        public static string GitHubNoReleasesAvailableString {
            get {
                return ResourceManager.GetString("GitHubNoReleasesAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Published ähnelt.
        /// </summary>
        public static string GitHubPublishedString {
            get {
                return ResourceManager.GetString("GitHubPublishedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release Notes ähnelt.
        /// </summary>
        public static string GitHubReleaseNotesString {
            get {
                return ResourceManager.GetString("GitHubReleaseNotesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GitHub Releases ähnelt.
        /// </summary>
        public static string GitHubReleasesString {
            get {
                return ResourceManager.GetString("GitHubReleasesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t notify about new releases ähnelt.
        /// </summary>
        public static string GitHubVersionNotificationDisabledString {
            get {
                return ResourceManager.GetString("GitHubVersionNotificationDisabledString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notify about new releases ähnelt.
        /// </summary>
        public static string GitHubVersionNotificationEnabledString {
            get {
                return ResourceManager.GetString("GitHubVersionNotificationEnabledString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string MessageDialogCancelString {
            get {
                return ResourceManager.GetString("MessageDialogCancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string MessageDialogOKString {
            get {
                return ResourceManager.GetString("MessageDialogOKString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number new releases ähnelt.
        /// </summary>
        public static string NumberNewReleasesString {
            get {
                return ResourceManager.GetString("NumberNewReleasesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number total releases ähnelt.
        /// </summary>
        public static string NumberReleasesTotalString {
            get {
                return ResourceManager.GetString("NumberReleasesTotalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Readme ähnelt.
        /// </summary>
        public static string ReadmeString {
            get {
                return ResourceManager.GetString("ReadmeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repair ähnelt.
        /// </summary>
        public static string RepairString {
            get {
                return ResourceManager.GetString("RepairString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository URL ähnelt.
        /// </summary>
        public static string RepositoryURLString {
            get {
                return ResourceManager.GetString("RepositoryURLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downgrade from v0.0.0 to v1.0.0 ähnelt.
        /// </summary>
        public static string UpdateStatusInfoDowngradeString {
            get {
                return ResourceManager.GetString("UpdateStatusInfoDowngradeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repair v0.0.0 ähnelt.
        /// </summary>
        public static string UpdateStatusInfoRepairString {
            get {
                return ResourceManager.GetString("UpdateStatusInfoRepairString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update from v0.0.0 to v1.0.0 ähnelt.
        /// </summary>
        public static string UpdateStatusInfoUpdateString {
            get {
                return ResourceManager.GetString("UpdateStatusInfoUpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are multiple options to update this version. Choose one of the options below. ähnelt.
        /// </summary>
        public static string UpdateUtilChooseSourceString {
            get {
                return ResourceManager.GetString("UpdateUtilChooseSourceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose update source ähnelt.
        /// </summary>
        public static string UpdateUtilChooseSourceTitleString {
            get {
                return ResourceManager.GetString("UpdateUtilChooseSourceTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm update ähnelt.
        /// </summary>
        public static string UpdateUtilConfirmUpdateTitleString {
            get {
                return ResourceManager.GetString("UpdateUtilConfirmUpdateTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For downgrades to lower versions, this update feature may not be available anymore! You have to download manually then! ähnelt.
        /// </summary>
        public static string UpdateUtilDowngradeWarningString {
            get {
                return ResourceManager.GetString("UpdateUtilDowngradeWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download from &lt;Path&gt; failed. ähnelt.
        /// </summary>
        public static string UpdateUtilDownloadFailedString {
            get {
                return ResourceManager.GetString("UpdateUtilDownloadFailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download failed ähnelt.
        /// </summary>
        public static string UpdateUtilDownloadFailedTitleString {
            get {
                return ResourceManager.GetString("UpdateUtilDownloadFailedTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to ähnelt.
        /// </summary>
        public static string UpdateUtilDoYouReallyWantToString {
            get {
                return ResourceManager.GetString("UpdateUtilDoYouReallyWantToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while update ähnelt.
        /// </summary>
        public static string UpdateUtilErrorString {
            get {
                return ResourceManager.GetString("UpdateUtilErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asset for Release v0.0.0 not found on GitHub. ähnelt.
        /// </summary>
        public static string UpdateUtilReleaseAssetNotFoundString {
            get {
                return ResourceManager.GetString("UpdateUtilReleaseAssetNotFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release asset not found ähnelt.
        /// </summary>
        public static string UpdateUtilReleaseAssetNotFoundTitleString {
            get {
                return ResourceManager.GetString("UpdateUtilReleaseAssetNotFoundTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installer must contain a Setup.exe file! ähnelt.
        /// </summary>
        public static string UpdateUtilSetupExeFailureString {
            get {
                return ResourceManager.GetString("UpdateUtilSetupExeFailureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To finish the update, the application is closed now. This may take some time. After the update is finished, the application is restarted. ähnelt.
        /// </summary>
        public static string UpdateUtilUpdateFinishedBinariesString {
            get {
                return ResourceManager.GetString("UpdateUtilUpdateFinishedBinariesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To finish the update, the application is closed now. Please use the started installer to reinstall the application. ähnelt.
        /// </summary>
        public static string UpdateUtilUpdateFinishedInstallerString {
            get {
                return ResourceManager.GetString("UpdateUtilUpdateFinishedInstallerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upgrade ähnelt.
        /// </summary>
        public static string UpgradeString {
            get {
                return ResourceManager.GetString("UpgradeString", resourceCulture);
            }
        }
    }
}
